files:
  - source: /app/src/main/res/values/
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    translatable_elements:
      - /app/src/main/res/values/strings.xml
      - /app/src/main/res/values/preferences.xml
